version: "3.9"
services:
  
  dns-internal:
    image: "internetsystemsconsortium/bind9:9.16"
    hostname: "dns"
    domainname: "woodytoys.internal"
    volumes: 
      - "./dns/internal/named.conf:/etc/bind/named.conf"
      - "./dns/internal/zones/:/etc/bind/zones/"
      - "./dns/internal/named.conf.local:/etc/bind/named.conf.local"
      - "./dns/internal/named.conf.options:/etc/bind/named.conf.options"
    networks: 
      internal-servers: 
        ipv4_address: "172.18.1.3"
  resolver-internal:
    image: "internetsystemsconsortium/bind9:9.16"
    volumes: 
      - "./dns/resolver/named.conf:/etc/bind/named.conf"
      - "./dns/resolver/named.conf.default_zones:/etc/bind/named.conf.default_zones"
      - "./dns/resolver/named.conf.local:/etc/bind/named.conf.local"
      - "./dns/resolver/named.conf.options:/etc/bind/named.conf.options"
    networks: 
      internal-servers: 
        ipv4_address: "172.18.1.5"
  
    
  pc-direction:
    image: "ubuntu"
    dns: "172.18.1.5"
    networks: 
      internal-computers: 
        ipv4_address: "192.168.0.2"
      internal-servers:
      dmz:
  pc-secretariat:
    image: "ubuntu"
    dns: "172.18.1.5"
    networks: 
      internal-computers: 
        ipv4_address: "192.168.0.3"
      internal-servers:
      dmz:
networks:
  dmz:
    ipam:
      config:
        - subnet: "172.18.3.0/24"
  internal-servers:
    ipam:
      config:
        - subnet: "172.18.1.0/24"
  internal-computers:
    ipam:
      config:
        - subnet: "192.168.0.0/16"
